---
title: "Chapter 8: Problems of Non-Democratic Consolidation and Control"
author: "Xavier Marquez"
date: "`r Sys.Date()`"
bibliography: bibfile.bib
output: 
  rmarkdown::html_vignette:
    toc: true
    keep_md: true
vignette: >
  %\VignetteIndexEntry{Chapter 8}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
# Introduction
  
This vignette shows how to replicate and extend the charts in chapter 8 of my book [*Non-democratic Politics: Authoritarianism, Dictatorships, and Democratization*](https://he.palgrave.com/page/detail/non-democratic-politics-xavier-marquez/?sf1=barcode&st1=9781137486301) (Palgrave Macmillan, 2016). It assumes that you have downloaded the replication package as follows:
  
```{r, echo = TRUE, eval = FALSE}
if(!require(devtools)) {
  install.packages("devtools")
}

devtools::install_github('xmarquez/AuthoritarianismBook')

```

```{r setup_chapter_8, include=FALSE}
knitr::opts_chunk$set(fig.height = 7, 
fig.width = 7)
```

Currently chapter 8 contains no figures.

